import { Fira_Code, Spicy_Rice } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import SmoothScrollProvider from "@/components/smoothScrollProvidor";
import Cursor from "@/components/cursor";
import Background from "@/components/background";

const spicyRice = Spicy_Rice({
  variable: "--font-spicy-rice",
  weight: "400",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Portfolio",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${spicyRice.variable} ${firaCode.variable}  antialiased relative min-h-screen w-full bg-[#121212] `}
      >
        <Background />
        <Navbar />
        <Cursor/>
        <SmoothScrollProvider>{children}</SmoothScrollProvider>
        
      </body>
    </html>
  );
}
